{% set name = "galsim_extra" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/esheldon/galsim_extra/archive/refs/tags/{{ version }}.tar.gz
  sha256: 60a2d844f3a13cbdef336c57efe8dcf88ffea3846ce6696aaa846b68806b07b0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - galsim
    - numpy
    - scipy
    - pixmappy
    - lsstdesc-coord

test:
  imports:
    - galsim_extra
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/esheldon/galsim_extra
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A package of modules that can be loaded in galsim config files

extra:
  recipe-maintainers:
    - beckermr
